services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/backend/data
      - ./backend/app/uploads:/app/backend/uploads
