services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/backend/data
      - uploads:/app/backend/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: "http://backend:8000"
      ORIGIN: "http://localhost:3000"
      BODY_SIZE_LIMIT: "Infinity"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - backend

volumes:
  uploads:
