name: Test Backend

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-backend:
    name: Run tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./dsa40applicationhelper/backend
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: uv sync --all-packages
    - name: Run backend tests
      run: uv run python -m pytest tests


